#!/usr/bin/env bash
# Generate a production .env for the center stack with strong random secrets.
# Never overwrite an existing environment unless --force is passed.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/../knowledge-hub"

if [[ -f .env && "${1:-}" != "--force" ]]; then
  echo "knowledge-hub/.env already exists; pass --force to overwrite it." >&2
  exit 1
fi

gen() {
  python3 -c 'import secrets; print(secrets.token_urlsafe(48))'
}
DB_PASSWORD="$(gen)"
PG_URL="postgresql+psycopg://knowledge:${DB_PASSWORD}@postgres:5432/knowledge"

cat > .env <<EOF
# Generated by scripts/init-production-env.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)
APP_ENV=production
DATABASE_URL=${PG_URL}
REDIS_URL=redis://redis:6379/0
TASK_EXECUTION_MODE=poll
ORCHESTRATION_MODE=state_machine
CELERY_QUEUE=knowledge-tasks
CELERY_HEALTH_TIMEOUT_SECONDS=0.5
MQTT_HOST=emqx
MQTT_PORT=8883
MQTT_TLS_ENABLED=true
MQTT_USERNAME=knowledge-hub-status-bridge
MQTT_PASSWORD=$(gen)
MQTT_CA_FILE=/run/mqtt-certs/ca.crt
MQTT_CLIENT_CERT_FILE=/run/mqtt-certs/bridge.crt
MQTT_CLIENT_KEY_FILE=/run/mqtt-certs/bridge.key
MQTT_BRIDGE_API_KEY=$(gen)
HUB_INTERNAL_URL=http://hub:8000
API_HOST=0.0.0.0
API_PORT=8000
NODE_OFFLINE_AFTER_SECONDS=90
FILE_MISSING_AFTER_SECONDS=300
REMOTE_COMMAND_LEASE_SECONDS=120
MAX_UPLOAD_BYTES=52428800
PARSE_CHUNK_CHARS=1000
REPLICA_NODE_IDS=
ADMIN_API_KEY=$(gen)
NODE_API_KEY=$(gen)
MOBILE_API_KEY=$(gen)
SEARCH_API_KEY=$(gen)
FLYWHEEL_INGEST_API_KEY=$(gen)
DOWNLOAD_API_KEY=$(gen)
EMBEDDING_PROVIDER=ollama
EMBEDDING_BASE_URL=http://ollama:11434
EMBEDDING_MODEL=bge-large-zh
EMBEDDING_DIMENSION=1024
EMBEDDING_TIMEOUT_SECONDS=10
EMBEDDING_ALLOWED_HOSTS=ollama,localhost,127.0.0.1
MAX_SEARCH_QUERY_CHARS=4000
MAX_SEARCH_TOP_K=20
DSH_ENABLED=false
DSH_BASE_URL=http://deepseek-harness:8010
DSH_API_KEY=
DSH_ALLOWED_HOSTS=localhost,127.0.0.1,deepseek-harness
STORAGE_BACKEND=local
STORAGE_ROOT=./storage
ALERT_CHANNELS=
ALERT_RETRY_MAX=3
ALERT_RETRY_BACKOFF_SECONDS=30
ALERT_SUPPRESS_WINDOW_SECONDS=300
SECURITY_SECRET=$(gen)
JWT_TTL_SECONDS=3600
BACKUP_DIR=./backups
BACKUP_RETENTION_DAYS=7
EOF

echo "Wrote knowledge-hub/.env (production)." >&2
echo "Next: ./scripts/generate-mqtt-certs.sh && ./scripts/deploy-center.sh" >&2
